---
title: "Untitled"
author: "KE Lotterhos"
date: "2024-03-25"
output: html_document
---

## Step 4: RDA between genotypes and phenotypes

Determine how this inversion influences traits

Questions for sara
- standardized for fish length?
  - 
- missing data?
- FYI, correlations


# Load packages and data
```{r load}
library(devtools)
library(bigstatsr)
library(bigsnpr)
library(ggplot2)
library(OutFLANK)
library(vegan)
library(pheatmap)
library(viridisLite)
library(heatmap3)
library(car)
library(multcompView)
library(multcomp)
library(tidyverse)
library(corrplot)
NCORES <- nb_cores()

datadir <- "/Users/lotterhos/Library/CloudStorage/GoogleDrive-k.lotterhos@gmail.com/.shortcut-targets-by-id/1DPJy8RgFslz3_PSZLLl7Z21mCvQUvnJZ/Manuscripts/Cod Ecotypes GoM /data/"

ggtheme <- theme_bw() + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), panel.border=element_blank(), axis.line = element_line(colour="grey30"), axis.title = element_text(colour="grey20"), axis.text = (element_text(colour="grey30")), legend.title = element_text(colour="grey20"), legend.text = element_text(colour="grey30"))

sessionInfo()


breakpoints <- read.csv("../outputs/1-breakpoints.csv") # breakpoints output from script 1

head(breakpoints)
LGtext <- breakpoints$LG 
LGtext

breakpoints$LGendPos-breakpoints$LGstartPos
breakpoints
```

```{r}
uncor_traits <- read.csv(paste0(datadir,"allSample_morphometrics-uncorrected.csv"))
cor_traits <- read.csv(paste0(datadir,"allSample_morphometrics_regressed.csv"))
samp_full <- readRDS("../outputs/2-Samples.rds")

head(uncor_traits)
head(cor_traits)
head(samp_full)

table(uncor_traits$Location,uncor_traits$Ecotype)
table(cor_traits$EcoLoc)

# align "uncorrected trait" data with samples in genotype matrix ####
uncor_traits$ID <- NA
uncor_traits$ID <- paste0(substr(uncor_traits$SampleID,1,2), substr(uncor_traits$SampleID,4,6))
head(uncor_traits$ID)
tail(uncor_traits$ID)
dim(uncor_traits)

cor_traits$ID <- NA
cor_traits$ID <- paste0(substr(cor_traits$SampleID,1,2), substr(cor_traits$SampleID,4,6))
head(cor_traits$ID)
tail(cor_traits$ID)
dim(cor_traits)

head(samp_full)
str(samp_full)
samp_full$order <- 1:nrow(samp_full)

# merge the traits into the sample dataframe 
samp_full2 <- merge(samp_full, uncor_traits, 
                    by.x = "samp_full", 
                    by.y = "ID", all.x=TRUE)

samp_full3 <- merge(samp_full2, cor_traits, 
                    by.x = "samp_full", 
                    by.y = "ID", all.x=TRUE)


samp_full4 <- samp_full3[order(samp_full3$order),]

# check the dimensions
if (dim(samp_full)[1] != dim(samp_full4)[1]) break()
if(!identical(samp_full$samp_full, samp_full4$samp_full)) break()

# Examine samples with genotypes but missing traits
missing <- is.na(samp_full4$D1)
sum(missing)
samp_full4$label[which(missing)]
```

# Visualize total length data
```{r length data}
### Examine length data


head(samp_full4)
samp_full4$Ecotype <- samp_full4$Ecotype.x

# Run ANOVA on population ID
poplm <- lm(TotalLength~PopID, data=samp_full4)
Anova(poplm)
anova <- aov(TotalLength~PopID, data=samp_full4)
t <- TukeyHSD(anova)
cld <- multcompLetters4(anova, t)

# Get Tukey letters for plot
clddf <- data.frame(cld$PopID$Letters)
clddf$PopID <- rownames(clddf)
clddf

# Get the order of the populations in the plot
# and merge the letters dataframe (which is not in the right order)
# with the ordered levels. Then make sure to reorder!
orderedPop <- data.frame(PopID=as.character(levels(samp_full4$PopID)))
orderedPop$order <- 1:nrow(orderedPop)
orderedPop
orderedPop <- merge(orderedPop, clddf, by="PopID")
orderedPop <- orderedPop[orderedPop$order,]
orderedPop

pdf("../figures/totalLength.pdf", width=8, height=6)
par(mar=c(8,4,1,1))
b <- boxplot(TotalLength~PopID, data=samp_full4, las=2, ylim=c(30,120))
text(1:9,y=120, orderedPop$cld.PopID.Letters)
plot(t, las=2)

is.ordered(samp_full4$PopID)
boxplot(TotalLength~Ecotype*Region, data=samp_full4, las=2)

is.ordered(samp_full4$LG1cluster_name)
levels(samp_full4$LG1cluster_name)
samp_full4$LG1cluster_name <- factor(samp_full4$LG1cluster_name, ordered=TRUE, levels = 
                            c("REF-GoM", "HET-GoM","REF-Iceland",
                              "HET-Iceland","ALT-Iceland"))
levels(samp_full4$LG2cluster_name)
samp_full4$LG2cluster_name <- factor(samp_full4$LG2cluster_name, ordered=TRUE, levels = 
                            c("REF-GoM", "HET-GoM", "ALT-GoM" ,"REF-Iceland",
                              "HET-Iceland","ALT-Iceland"))
levels(samp_full4$LG7cluster_name)
samp_full4$LG7cluster_name <- factor(samp_full4$LG7cluster_name, ordered=TRUE, levels = 
                            c("REF-GoM", "HET-GoM", "ALT-GoM" ,"REF-Iceland",
                              "HET-Iceland","ALT-Iceland"))
levels(samp_full4$LG12cluster_name)
samp_full4$LG12cluster_name <- factor(samp_full4$LG12cluster_name, ordered=TRUE, levels = 
                            c("REF-GoM", "HET-GoM", "ALT-GoM" ,"REF-Iceland",
                              "HET-Iceland","ALT-Iceland"))

boxplot(TotalLength~LG1cluster_name, data=samp_full4, las=2)
boxplot(TotalLength~LG2cluster_name, data=samp_full4, las=2)
boxplot(TotalLength~LG7cluster_name, data=samp_full4, las=2)
boxplot(TotalLength~LG12cluster_name, data=samp_full4, las=2)
dev.off()



samp_full4$LG1cluster_nameB <- substr(samp_full4$LG1cluster_name,0,3)
head(samp_full4$LG1cluster_nameB)
table(samp_full4$LG1cluster_nameB,samp_full4$Region)
try(Anova(lm(TotalLength~LG1cluster_nameB*Region, data=samp_full4, 
      contrasts=list(LG1cluster_nameB='contr.sum', Region='contr.sum')),
      type='III'))
# this model is missing datapoints in one factor combination, so it throws an error

samp_full4$LG2cluster_nameB <- substr(samp_full4$LG2cluster_name,0,3)
table(samp_full4$LG2cluster_nameB,samp_full4$Region)
Anova(lm(TotalLength~LG2cluster_nameB*Region, data=samp_full4, 
      contrasts=list(LG2cluster_nameB='contr.sum', Region='contr.sum')),
      type='III')

samp_full4$LG7cluster_nameB <- substr(samp_full4$LG7cluster_name,0,3)
table(samp_full4$LG7cluster_nameB,samp_full4$Region)
Anova(lm(TotalLength~LG7cluster_nameB*Region, data=samp_full4, 
      contrasts=list(LG7cluster_nameB='contr.sum', Region='contr.sum')),
      type='III')

samp_full4$LG12cluster_nameB <- substr(samp_full4$LG12cluster_name,0,3)
table(samp_full4$LG12cluster_nameB,samp_full4$Region)
Anova(lm(TotalLength~LG12cluster_nameB*Region, data=samp_full4, 
      contrasts=list(LG12cluster_nameB='contr.sum', Region='contr.sum')),
      type='III')
```



```{r}
# read in a genotype matrix to get the sequenced individuals
G_LGX <- readRDS(paste0("../outputs/1-G_",LGtext[1],".rds"))

pos <- colnames(G_LGX)
samp <- rownames(G_LGX)

# make sure clusters are lined up
plot(samp_full4$LG1_PC1, samp_full4$LG1_PC2, col=samp_full4$LG1cluster_name)

# Create a data frame to hold the sample data for the rDA
samp_full4_gen <- data.frame(label=samp, order_G=1:length(samp))
samp_full4_gen <- left_join(samp_full4_gen, samp_full4)
head(samp_full4_gen)
plot(samp_full4_gen$LG1_PC1, samp_full4_gen$LG1_PC2, col=samp_full4_gen$LG1cluster_name)

# Get the corrected trait values
traitcols <- which(colnames(samp_full4_gen) %in% paste0("cD", 1:22))
traitcols
colnames(samp_full4_gen)[traitcols]





# check the sample dataframe samp_full# check the sample dataframe is identical
if (!identical(samp_full4_gen$label, samp)){print("Error"); break()} 

# get the rows that don't have NA for trait values
samprows <- which(!is.na(samp_full4_gen$cD1))
length(samprows)

samp_full5_gen <- samp_full4_gen[samprows,]
  
# check trait correlations
cortraits <- cor(samp_full5_gen[, traitcols])
corrplot(cortraits)
heatmap(cortraits, scale="none")

# use clustering to choose representative traits
trait_groups <- cutree(hclust(dist(cortraits, diag=TRUE)), k=9)
trait_groups
write(trait_groups,"../outputs/traitgroups.txt")

# Determine subset of representative traits
subtraits = c("cD1", "cD3", "cD4", "cD5", "cD10", "cD13", "cD16", "cD18", "cD19") # hard coding!

subTraitCols <- which(colnames(samp_full5_gen) %in% subtraits)
# check trait correlations
cortraits2 <- cor(samp_full5_gen[, subTraitCols])
cortraits2 # all correlations are less than 0.75

pdf("../figures/RDA_trait_corrs.pdf", width=7, height=7)
corrplot(cortraits2)
heatmap(cortraits2, scale="none")
dev.off()

#complete data for RDA
rda_traits <- scale(samp_full5_gen[,subTraitCols])
summary(rda_traits)

rownames(rda_traits) <- samp_full5_gen$label
dim(rda_traits)
head(rda_traits)
```

```{r, rda_trait_pred function}
rda_trait_pred <- function(rdaobj, env_row, K){
  #rdaobj is RDA object
  #env_row is the row of the environment in the biplot output
  #K is the number of RDA axes
  scores <- scores(rdaobj, choices=1:K)
  ind.sc <- scores$sites
  pred <- matrix(NA, nrow=nrow(ind.sc), ncol=K)
  for (k in 1:K){
    pred[,k] <- ind.sc[,k]*eigenvals(rdaobj)[k]*summary(rdaobj)$biplot[env_row,k]
  }
  trait_pred <- scale(rowSums(pred))
 return(trait_pred) 
}

```

```{r rdas}


samp_inv_morph_full <-  NULL

for (i in 1:4){
  samp_inv_morph <- data.frame(label = rownames(rda_traits),
                             Inv = LGtext[i],
                             traitname = NA,
                             trait_pred = NA)
  print(LGtext[i])
#i=1
G_LGX <- readRDS(paste0("../outputs/1-G_",LGtext[i],".rds"))
muts <- readRDS(paste0("../outputs/2-",LGtext[i],"-muts.rds"))
dim(muts)

# make sure dimensions line up
if(!(dim(G_LGX[samprows,])[1]==dim(samp_full5_gen)[1])){
  print("Error dim don't line up")
  break
  }# make sure labels line up
if(!identical(rownames(G_LGX[samprows,]),samp_full5_gen$label)){
  print("Error sample names don't line up")
  break
  }# make sure labels line up

pos <- colnames(G_LGX)

G_LGX2 <- add_code256(big_copy(G_LGX[samprows,] ,type="raw"),code=bigsnpr:::CODE_012)

### Snp thinning
# Use this function to perform clumping and pruning on snps in large windows. We'll use this subset of "less" linked snps for the rDA
# To skip this step comment out these lines
# we give the infos.chr the same ID because we do one inversion at a time
pca_inv <- snp_autoSVD(G_LGX2,infos.chr=rep(1, length=length(muts$pos)), infos.pos = muts$pos,
                   size= 50000000,
                    thr.r2=0.1
                   )
# size is the window size around the snp. 
# For LG1, A size of 100,000 and r2 threshold 0.2 reduces the 74,000 snps on LG1 to 17,000. A size of 50MB and threshold 0.1 reduces to 8,000.
# I explored the effects of thinning and the pattern in the results were not super sensitive to these parameters. With fewer SNPs, the percent of variation explained by the first two RDA axis decreased. In addition, for LG2 and LG7, there was more spread around individuals in RDA space. But for LG1 and LG12, strong clustering remained in RDA space.
#str(pca_inv)
#dim(G_LGX2)
thinned_snps <- attr(pca_inv, which="subset")
print("number of snps")
dim(G_LGX2)[2]
print("number of thinned snps")
length(thinned_snps)
pca_inv$cluster_name <-samp_full5_gen[,paste0(LGtext[i],"cluster_name")]
str(pca_inv)
# just a quick check that everything lines up
plot(pca_inv$u[,1], pca_inv$u[,2], col=pca_inv$cluster_name)
#### end snp thinning


rda_gen <- G_LGX[samprows,thinned_snps]
dim(G_LGX)
dim(rda_gen) 

# check the sample dataframe issamp_full# check the sample dataframe is identical
if (!identical(rownames(rda_traits), rownames(rda_gen))){print("Error"); break()} 

rda_lgx <- rda(rda_gen~rda_traits)

# eigenvalues
a<- screeplot(rda_lgx)
eigen <- a$y
# proportion of expl. variance for each RDA axis
prop_var <- round(a$y/sum(a$y),3)
print(prop_var)
# cumulative proportion of variance
cumsum(prop_var)
print(cumsum(prop_var))

K=4

# Save loadings output
biplot <- (as.data.frame(rda_lgx$CCA$biplot[,1:K]))
print(biplot)
cumimpmat <- abs(t(biplot)*prop_var[1:K])
colnames(cumimpmat) <- subtraits

#plot cum imp
pdf(paste0("../figures/",LGtext[i],"_RDACumImp.pdf"), width=7, height=4)
  barplot(cumimpmat, las=2, xlim=c(0,15), 
          main=LGtext[i], 
          col=grey.colors(4, start=0.3, end=0.9), 
          ylab="Cumulative Importance")
  legend("right", paste0("RDA ",4:1,", ",
                        round(prop_var[4:1],2)*100,"%"),
         bty="n", adj=0, 
         fill=grey.colors(4, start=0.9, end=0.3),
         cex=1)
dev.off()

biplot$cumImp <- colSums(cumimpmat)
biplot <- rbind(biplot, c(prop_var[1:K], NA))
rownames(biplot)[nrow(biplot)] <- "Prop_Var"
biplot
write.table(biplot, file=paste0("../outputs/RDA_biplot_", LGtext[i],".txt"))

# loop through each trait and get the predicted value from the RDA
for (j in 1: (nrow(biplot)-1)){
  samp_inv_morph$traitname <- rownames(biplot)[j]
  samp_inv_morph$trait_pred <- rda_trait_pred(rda_lgx, j, K)
  samp_inv_morph_full <- rbind(samp_inv_morph_full,samp_inv_morph)
}



scores <- scores(rda_lgx)
str(scores)

samp_full5_gen[,paste0(LGtext[i],"RDA1")] <- scores$sites[,1]
samp_full5_gen[,paste0(LGtext[i],"RDA2")] <- scores$sites[,2]
 
max=max(c(scores$sites[,1], scores$sites[,2]))
min=min(c(scores$sites[,1], scores$sites[,2]))
#plot(rda_lgx, xlim=c(min,max), ylim=c(min,max))

# double check the names line up!
bp <- data.frame(scores$biplot*max)
bp$names <- subtraits
bp
rownames(bp) <- subtraits
bp


#Plot
samp_full5_gen$Ecotype2 <- paste0(samp_full5_gen$Ecotype.x,"-",
                                 samp_full5_gen$Region)
g3 <- ggplot() + ggtheme + 
  geom_point(data=samp_full5_gen, 
             aes(x=get(paste0(LGtext[i],"RDA1")),
                y=get(paste0(LGtext[i],"RDA2")),
            shape=get(paste0(LGtext[i],"cluster_nameB")),
            color=Ecotype2
    )) + scale_color_manual(values=c("lightblue","cornflowerblue","darkviolet")) +
  geom_segment(data=bp, 
               aes(x=0, y=0, 
                   xend=RDA1, 
                   yend=RDA2),color="grey") + 
  geom_text(data=bp, 
            aes(x=RDA1, y=RDA2, 
                label=names), hjust=0) + 
  xlab(paste0("RDA1 (", round(biplot["Prop_Var",1],2)*100,"%)"))+
  ylab(paste0("RDA2 (", round(biplot["Prop_Var",2],2)*100,"%)")) + 
  theme(legend.title = element_blank()) + 
  ggtitle(LGtext[i])
g3
ggsave(filename=paste0("../figures/",LGtext[i],"_RDA_3.pdf"), g3, width = 5, height=4)
} # end loop

head(samp_full2)
```

# Trait prediciton
```{r, trait prediction}

traittext <- unique(samp_inv_morph_full$traitname)
subtraits


i=1
sub <- samp_inv_morph_full[samp_inv_morph_full$traitname==traittext[i],]
str(sub)
sub$label <- as.factor(sub$label)
sub$Inv <- as.factor(sub$Inv)
head(sub)
if(!dim(sub)[1]/255==4){print("Error in dimensions");break} #this should be four
sub$trait <- rda_traits[,subtraits[i]]
head(sub)

sub$color <- 

rda_traits <- as.data.frame(rda_traits)
str(rda_traits)
rda_traits2<- rda_traits[order(rda_traits$cD1),]
rda_traits2$label <- rownames(rda_traits2)
head(rda_traits2)
g2a <- ggplot(data=sub, aes(x=trait_pred, y=label)) +
  geom_bar(stat="identity")
g2a
barplot(t(sub[order(sub$label),"trait_pred"]), horiz=TRUE)

ggsave(filename=paste0("../figures/RDA_cD1_values.pdf"), g2a, width = 15, height=20)


g2 <- ggplot(data=sub, aes(fill=Inv, x=trait_pred, y=cD1_order)) + 
           geom_bar(position="stack", stat="identity") 
g2
ggsave(filename=paste0("../figures/RDA_cD1_predict.pdf"), g2, width = 15, height=20)
```
